version: '3.9'

services:
  frontend:
    image: biton2026/blockscout-frontend:v2.3.5.1
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
